---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: octohost
    driver:
      box: darron/octohost
      vm_hostname: octohost

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[octoregistrator::default]
    attributes:
